### ISSUE TITLE
Back-End Login Route

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#1]
Create route for login with "/user/login"

**Comment by shahdjaouni** [comment]
I named this route (/signIn).
this task has one problem when I am entering  a wrong username the server is crashed . 
I tried many ways but it was incorrect . 
Do you have any suggestions to solve this problem ??

**Comment by osamaths** [comment]
can you send me you code or screenshot of it

**Comment by osamaths** [comment]
be careful to the name of the route to be the same as the description

**Comment by shahdjaouni** [comment]
Ok sir , I will send a screenshot on Slack .

**Comment by shahdjaouni** [comment]
I changed the route name .
