### ISSUE TITLE
Back-End Learn how to make relationship between two collections

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#18]

**Comment by shahdjaouni** [comment]
I am working on it .. I did not find actually solution , but I learnt a lot of things , I am too close to figure it out  , so I will keep trying .

**Comment by shahdjaouni** [comment]
Done :) at 2:39 am 8/5/2018

**Comment by osamaths** [comment]
Thank you :) but the time is mentioned in the comment upove saying 7 hours ago :-P
