### ISSUE TITLE
Front-End Navigation System

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#24]

**Comment by osamaths** [comment]
I created tabNavigation for LOGIN and SIGNUP, and connected them using StackNavigator with News.

**Comment by osamaths** [comment]
I lost the changes, I will re-do it again.

**Comment by shahdjaouni** [comment]
okay , no problem and thank you for your effort :)

**Comment by osamaths** [comment]
Thanks.

**Comment by osamaths** [comment]
Finish the navigation system, now once we open the app we see Login and Signup Tabs, Then we will go to News and AddNews Tabs.
