### ISSUE TITLE
Back-End Signup Route

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#3]
route "/user/singup"

**Comment by shahdjaouni** [comment]
I named this route (/signUp/newuser) . 
This task is officially done and it has no problem .

**Comment by osamaths** [comment]
Great. But I named the route to be like the descreption above.

**Comment by shahdjaouni** [comment]
yah ,, but because when I started this work the waffle wasn't work , so I put the name 
Do you wanna from me to change it ??

**Comment by shahdjaouni** [comment]
I changed the route name .
