### ISSUE TITLE
Back-End Check user exist before create new

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#32]

**Comment by shahdjaouni** [comment]
This task is done , and I changed the year field to DOB

**Comment by osamaths** [comment]
Can you explain what is DOB ?

**Comment by shahdjaouni** [comment]
yes sure , when you show me the front-end signup I saw a (date of birth) for every user so I decided to convert it .

**Comment by osamaths** [comment]
No that was for test only. Year now is number.

**Comment by shahdjaouni** [comment]
The enhancement was done .

**Comment by osamaths** [comment]
Okay nice,  you can move to "Done"
