### ISSUE TITLE
Back-End Add "isAmira" to User Schema

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#34]
اضف اميرة الى دوركيومنت اليوزر واضف ايضا من اسمع لهم على شكل مصفوفة

**Comment by shahdjaouni** [comment]
var AmiraSchema = new Schema({

  name: String,
  year:Number,
  people:[{
    type : Schema.Types.ObjectId,
    ref : 'user'
}]
});
DONE

**Comment by osamaths** [comment]
No I meant add "Amira" as a field in the user schema. Not create a whole new schema.

**Comment by shahdjaouni** [comment]
ohhh , I did not get the point you were talking about .

**Comment by shahdjaouni** [comment]
Done , I put ((isAmira : Boolean)) field in User schema .

**Comment by osamaths** [comment]
Great, you can make it "Done"
