### ISSUE TITLE
Back-End Add "Amira" routes

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#35]
Make routes to handle choosing Amira.

**Comment by shahdjaouni** [comment]
In this route we found the (Amira) then put the users who are learning Quran from her in the array of string called people,  and found (Users) then put the current amira for them .

**Comment by shahdjaouni** [comment]
This task should has enhancement  for test length .

**Comment by osamaths** [comment]
Okay thanks I will add one now. And you free to move it "Done"

**Comment by shahdjaouni** [comment]
You mean that you add another ticket for length enhancement ?

**Comment by osamaths** [comment]
Yes.
