### ISSUE TITLE
Back-End User Schema

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#4]
create collection on mongoose for normal user

**Comment by shahdjaouni** [comment]
kkjggg

**Comment by shahdjaouni** [comment]
I finished this Schema.
I put this object 
var UserSchema = new Schema({
  gender: Boolean,
  username: String,
  email:String,
  password:String,
  year:Number
});
NOTE : gender is like unique ID

**Comment by shahdjaouni** [comment]
Is there any ideas can I do to improve this task ??

**Comment by osamaths** [comment]
Nice work, But do you mean by year?

**Comment by shahdjaouni** [comment]
Thanks , I mean the educational year if you're in first year ,second year ... and last year

**Comment by osamaths** [comment]
Ah ok thank you .
