### ISSUE TITLE
Back-End Create Halqa Schema

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#42]
Has these keys:
1- name
2- teacher
3- students
4- time
5- place

**Comment by shahdjaouni** [comment]
This task was done with below stander ed :
var HalaqaSchema = new Schema({
  name: String,
  teacher: String,
  students:[String],
  time:String,
  place: String
  });

**Comment by osamaths** [comment]
If you tested it, move it to "Done"
