### ISSUE TITLE
Back-End Create Halqa Route

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#43]
route "create/halqa" POST

**Comment by shahdjaouni** [comment]
This task finished ,
so we create (name , teacher, time , place ) for every halqa ,
and students I created another route for it called "/add/student/halqa"

**Comment by shahdjaouni** [comment]
I need to test these two routes in professional way so move this task to In progress .

**Comment by osamaths** [comment]
Good, thanks.
