### ISSUE TITLE
Front-End Login Component

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#6]

**Comment by shahdjaouni** [comment]
Well-done :)

**Comment by osamaths** [comment]
Finish this ticket , but still need UI which will be in another Ticket(Story) in another *Sprint*.
@shahdjaouni 
PS. Read about Sprint and Story in Scrum.

**Comment by shahdjaouni** [comment]
Done

**Comment by osamaths** [comment]
I added a new ticket for you , please write "Done" there.
@shahdjaouni
