### ISSUE TITLE
Back-End Male , Female

### ISSUE THREAD

**Issue by shahdjaouni** [Kashams-Lldonia/kashams_lldonia#69]
Divide the process of logging based on the gender

**Comment by shahdjaouni** [comment]
This is my code and it is resulted correctly, What should I do now ? 

//get amiras
app.get("/get/all/amiras", (req, res) => {
  User.find({ userType: "amira", gender: "male" }, (err, user) => {
    if (user) res.send(user);
  });
});

**Comment by osamaths** [comment]
Nice work, just try to change "male" to req.body.gender. to make it dynamic.
Great work, keep it up.

**Comment by shahdjaouni** [comment]
Thanks Osama , I will
