### ISSUE TITLE
Front-End Signup Component

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#7]

**Comment by osamaths** [comment]
With testing on server:
1- I think you need to change the gender to be enum with "Male or Female".
2- You need to check if the user exist before creating one on sign up

cc: @shahdjaouni

**Comment by shahdjaouni** [comment]
okay .. I will solve this tomorrow .

**Comment by osamaths** [comment]
Okay, good luck.

**Comment by shahdjaouni** [comment]
Thank you .

**Comment by shahdjaouni** [comment]
Done
