### ISSUE TITLE
Front-End Login Request

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#8]
Route on "/user/login"

**Comment by osamaths** [comment]
I need the "response" if was correct to return "true" and if was not to return "{message: the message"}

**Comment by osamaths** [comment]
@shahdjaouni

**Comment by shahdjaouni** [comment]
I don't get it .

**Comment by osamaths** [comment]
Like the image below

![Screenshot from 2018-05-08 10-01-37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd0c510aaed900114f237b/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd5bb68ee1236515e424dab53444d04bea6d37ef5f22e7a98595ab9d36d0e7dc13944a8bb8b49bf01bb72884dd0b0edde5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5af34ce74f5ca1123761e6647b.png)

**Comment by osamaths** [comment]
Finish this ticket

**Comment by shahdjaouni** [comment]
Done

**Comment by osamaths** [comment]
Thank you. Can you make a pull request?

**Comment by shahdjaouni** [comment]
Sure , after I finished last task .

**Comment by osamaths** [comment]
Okay, don't forget to commit after each success :D
