### ISSUE TITLE
Front-End Signup Request

### ISSUE THREAD

**Issue by osamaths** [Kashams-Lldonia/kashams_lldonia#9]
On Route "/user/signup"

**Comment by osamaths** [comment]
I need the "response" if was correct to return "true" and if was not to return "{message: the message"}

**Comment by osamaths** [comment]
@shahdjaouni

**Comment by shahdjaouni** [comment]
I don't get it .

**Comment by osamaths** [comment]
Same as the image below.


![Screenshot from 2018-05-08 10-01-37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd0c510aaed900114f237b/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f37e3dd5bb68ee1236515e424dab53444d04bea6d37ef5f22e7a98595ab9d36d0e7dc13944a8bb8b49bf01bb72884dd0b0edde5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5af34ce74e55a7123464e0647b.png)

**Comment by osamaths** [comment]
Finish This Ticket

**Comment by shahdjaouni** [comment]
Done
